version: '3'

services:

  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=5432
    volumes:
      - ./.postgres-data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
       - "5432:5432"
    env_file:
      - ./.env.prod.db

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: >
      sh -c "gunicorn base.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq: # login guest:guest
    image: rabbitmq:management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: >
      sh -c "celery -A base.celery worker --loglevel=info"
    ports: []
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - db
      - web

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  .postgres-data: