version: '3'

services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: always
    command: >
      sh -c "gunicorn base.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq: # login guest:guest
    image: rabbitmq:management
    restart: always
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    restart: always
    command: >
      sh -c "celery -A base.celery worker --loglevel=error"
    ports: []
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - web

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web