# Generated by Django 3.0.2 on 2020-01-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_divulgacao', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstagioCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio_cancer', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_faixa', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fornecedor', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapeamentoPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacao', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('whatsapp', models.CharField(max_length=50, null=True)),
                ('cnpj', models.CharField(max_length=15, null=True)),
                ('cnes', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Informações Cadastrais Ong',
            },
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parceiro', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeVoluntarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioCenso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pergunta', models.IntegerField(null=True)),
                ('secao', models.IntegerField(null=True)),
                ('pergunta', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Questões do Censo',
            },
        ),
        migrations.CreateModel(
            name='SistemaSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sistema', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cancer', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parceria', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoOng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=50, null=True)),
                ('score', models.IntegerField(null=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ong')),
            ],
            options={
                'verbose_name_plural': 'Segmento da Ong',
            },
        ),
        migrations.CreateModel(
            name='ScoreRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.IntegerField(null=True)),
                ('alternativa', models.CharField(max_length=200, null=True)),
                ('peso', models.IntegerField(null=True)),
                ('advocacy', models.IntegerField(null=True)),
                ('proximidade_femama', models.IntegerField(null=True)),
                ('maturidade_data', models.IntegerField(null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.QuestionarioCenso')),
            ],
            options={
                'verbose_name_plural': 'Peso das Perguntas',
            },
        ),
        migrations.CreateModel(
            name='CensoRespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_censo', models.IntegerField(null=True)),
                ('resposta', models.TextField(null=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ong')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.QuestionarioCenso')),
            ],
            options={
                'verbose_name_plural': 'Respostas do Censo',
            },
        ),
    ]
